FROM nginx:1.21.1-alpine

#config
copy ./nginx.conf /etc/nginx/nginx.conf

#content, comment out the ones you don't need!
copy ./*html /usr/share/nginx/html/
# copy ./css /usr/share/nginx/html/css
# copy ./js /usr/share/nginx/html/js
# copy ./png /usr/share/nginx/html/png